#!/bin/bash -f
# Copyright (c) 2012, The SAVI Project.
# Eliot J. Kang

# you need to run "source devi/savienvrc <username> <tenantname>"
# before running this file
if [[ -z $SAVI_USER ]]; then
  echo "First, source devi/savienvrc <username> <tenantname>"
  exit
fi
java -jar $SAVI_HW_JAR -u $SAVI_USER -p $SAVI_PASSWORD -c list_res \
-l $SAVI_LOCATION -wsdl $CONTROL_WSDL
